### ISSUE TITLE
why "allIds" state?

### ISSUE THREAD

**Issue by mathieuprog** [gaearon/todos#7]
I was wondering what is the reason to keep an array containing all the ids of the todos. An array of ids can be obtained by calling Object.keys() on the normalised state. I see this pattern reoccurring in other redux related tutorials.

**Comment by mwarger** [comment]
Dan briefly explains this in the 11th episode of his egghead.io course "[Building React Applications with Idiomatic Redux](https://egghead.io/lessons/javascript-redux-normalizing-the-state-shape)."  It's kept in an array separately because you could have todo representations spread out in multiple parts of your app.  An array of IDs provides a single source of truth for your whole list of todos.  You could imagine having different todos (in this case a metaphor for any entity in your model) in different places.  As you mentioned, you could call Object.keys() on one of them.  But what if you have many?  You would have to keep track of where and what they are, or otherwise managing the list.  Keeping it centralized allows you to see the whole, without needing the parts.

I'm learning along the way, so please let me know if this is confusing or if I've goofed up somewhere.  

Also, I could be wrong about this... so if you see any problems with this logic let me know.
